apiVersion: apps/v1
kind: Deployment
metadata:
  name: haystack-api
spec:
  replicas: {{ .Values.haystack.replicas }}
  selector:
    matchLabels:
      app: haystack-api
  template:
    metadata:
      labels:
        app: haystack-api
    spec:
      containers:
        - name: haystack
          image: {{ .Values.haystack.image }}
          command: ["haystack"]
          args:
            - "api"
            - "--config"
            - "/app/pipeline_config.yaml"
          resources:
            requests:
              memory: {{ .Values.haystack.resources.requests.memory }}
              cpu: {{ .Values.haystack.resources.requests.cpu }}
            limits:
              memory: {{ .Values.haystack.resources.limits.memory }}
              cpu: {{ .Values.haystack.resources.limits.cpu }}
          volumeMounts:
            - name: pipeline-config
              mountPath: /app
      volumes:
        - name: pipeline-config
          configMap:
            name: pipeline-config