apiVersion: apps/v1
kind: Deployment
metadata:
  name: haystack-solution-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haystack-ui
  template:
    metadata:
      labels:
        app: haystack-ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          resources:
            requests:
              memory: 64Mi
              cpu: 25m
            limits:
              memory: 128Mi
              cpu: 50m
          ports:
            - containerPort: {{ .Values.ui.port }}