apiVersion: apps/v1
kind: Deployment
metadata:
  name: haystack-streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haystack-streamlit-ui
  template:
    metadata:
      labels:
        app: haystack-streamlit-ui
    spec:
      containers:
        - name: streamlit-ui
          image: streamlit/streamlit:latest
          command: ["streamlit", "run"]
          args: ["/app/ui_app.py", "--server.port=8501", "--server.enableCORS=false"]
          volumeMounts:
            - name: ui-code
              mountPath: /app
          ports:
            - containerPort: 8501
      volumes:
        - name: ui-code
          configMap:
            name: streamlit-ui-code
