apiVersion: v1
kind: Service
metadata:
  name: resume-uploader
spec:
  type: {{ .Values.service.type }}
  selector:
    app: resume-uploader
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.uploader.port }}
