components:
  - name: retriever
    type: EmbeddingRetriever
    params:
      embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

  - name: reader
    type: FARMReader
    params:
      model_name_or_path: deepset/roberta-base-squad2

  - name: document_store
    type: QdrantDocumentStore
    params:
      host: qdrant
      embedding_dim: 384
