haystack:
  image: deepset/haystack:latest
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m

qdrant:
  image: qdrant/qdrant:latest
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m

ui:
  image: streamlit/streamlit:latest
  port: 8501

uploader:
  image: myorg/resume-uploader:latest
  port: 3000

service:
  type: ClusterIP
