---
haystack:
  image: deepset/haystack:cpu-v1.26.4
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 128Mi
      cpu: 50m

ui:
  image: streamlit/streamlit:latest
  enabled: true
  port: 8501
  service:
    type: LoadBalancer
    port: 80

uploader:
  image: downloads.unstructured.io/unstructured-io/unstructured:latest
  port: 3001
  enabled: true
  command: ["python3", "-m", "unstructured.ingest.interfaces.api.main"]
  args: ["--destination", "qdrant", "--api-url", "http://haystack-api:8000/documents"]

qdrant:
  image: qdrant/qdrant:v1.7.3
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m

service:
  type: ClusterIP
