haystack:
  image: deepset/haystack:cpu-v1.26.4
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

qdrant:
  image: qdrant/qdrant:v1.7.3
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

ingress:
  enabled: true
  host: haystack.local
