haystack:
  image: deepset/haystack-api:1.20.0
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 128Mi
      cpu: 50m

ui:
  image: deepset/haystack-ui:1.20.0
  port: 8501

uploader:
  image: ghcr.io/your-org/resume-uploader:1.0.0
  port: 3000

qdrant:
  image: qdrant/qdrant:v1.7.3
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m

service:
  type: ClusterIP
