apiVersion: apps/v1
kind: Deployment
metadata:
  name: haystack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haystack-api
  template:
    metadata:
      labels:
        app: haystack-api
    spec:
      containers:
        - name: haystack
          image: {{ .Values.haystack.image }}
          resources:
            requests:
              memory: {{ .Values.haystack.resources.requests.memory }}
              cpu: {{ .Values.haystack.resources.requests.cpu }}
            limits:
              memory: {{ .Values.haystack.resources.limits.memory }}
              cpu: {{ .Values.haystack.resources.limits.cpu }}
          ports:
            - containerPort: 8000